### ISSUE TITLE
No coverage displayed after sending valid lcov report

### ISSUE THREAD

**Issue by devs-deep** [codacy/node-codacy-coverage#19] opened 2015-11-23 14:22 UTC
No coverage displayed after sending valid lcov report.

1. Generate lcov report by using istanbul and istanbul-combine. 
2. Send it to codacy (CODACY_PROJECT_TOKEN was configured in travis CI)

Note: Need to take into account that this steps works fine in previous releases.

**Comment by machadoit** [comment] 2015-11-23 14:41
Hi,
The last version we have released is 1.1.3, and it was some months ago.
When it was working fine? Which version are you referring to?

**Comment by vcernomschi** [comment] 2015-11-24 09:20
Hi,

I also use 1.1.3. It worked fine approx. 10 days ago (I suppose before Nov, 16th changes). 

I am using the following JS code coverage tools:
 - istanbul 0.4.0 to generate reports
 - istanbul-combine 0.3.0 to combine reports

Please refer to the attached lcov.info file (was renamed to lcov.info.txt be able to be uploaded)

[lcov.info.txt](https://github.com/codacy/node-codacy-coverage/files/42525/lcov.info.txt)

**Comment by machadoit** [comment] 2015-11-24 10:05
How are you using node-codacy coverage? Are you installing with npm?

If you are using npm, you will get the 1.1.3 version, that is stable. The changes we made in this repository are not deployed yet. Or are you using the source directly from master?

**Comment by vcernomschi** [comment] 2015-11-24 15:36
Yes, we install it with npm: 

`npm install -g codacy-coverage@1.1.3`

**Comment by machadoit** [comment] 2015-11-25 11:16
Hi, 
We are contacting you via the Codacy chat, so we can solve your issue.

**Comment by machadoit** [comment] 2015-11-25 11:29
What is the exact error you having? In which project are you having the issue? Can you see anything in the output? And can you send us the coverage file that is generated by instanbul?

Contact us trough Codacy Intercom or email us to team@codacy.com when you have website interaction issues for a more custom and faster response.

**Comment by vcernomschi** [comment] 2015-11-29 13:18
I am not getting any errors during sending coverage report to codacy from command line.  

On codacy I can see issue below for "Validate report" stage:
Oops!
There's something wrong with the report we received. Ping us on the support chat, and we'll help you figure it out.
Here some usual causes that might be causing problems:
Outdated reporter: Always make sure you're running an up-to-date version of the reporter.
Inconsistent file paths: Depending on your project structure, Codacy may be unable to automatically detect the files identified in coverage report. The reporters have special options to normalise the project root folder, check their documentation.

The issue is reproducible for all our public and private projects.

Please refer to the attached coverage file (lcov.info.txt) that is generated by instanbul.
[lcov.info.txt](https://github.com/codacy/node-codacy-coverage/files/46606/lcov.info.txt)

**Comment by pedrorijo91** [comment] 2015-11-29 13:33
@vcernomschi As far as I can see, on Codacy you don't have any coverage reports received. For @devs-deep we found 3 projects, only 1 with coverage: `deep-microservices-account`

To that project we are receiving reports with filenames like: `../../Frontend/js/app/angular/name.js`
Those kind of filenames do not match any codacy file. Codacy would expect some filename like `src/DeepAccount/Frontend/js/app/angular/name.js`

Please make sure the correct filename is provided as expected.

> Note: we tried to contact both accounts through intercom but we received no answer. Please, next time contact us trough intercom, available at Codacy platform in https://www.codacy.com/, so we can talk about your particular case since it's not a tool issue.

**Comment by pedrorijo91** [comment] 2015-11-30 12:12
Closing as not tool related.

**Closed by pedrorijo91** 2015-11-30 12:12 UTC
